version: '3.0'
services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3307"
    networks:
      - mysql_network
    restart: unless-stopped
networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
