version: '3'
services:
  spring-app:
    image: jobcompanyreview
    container_name: spring-app
    build: .
    ports:
      - "9001:9001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3307/youtube_learning_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Use this for setting root password
      MYSQL_DATABASE: youtube_learning_db # Initial database creation
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
